[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "git_chatbot"
version = "0.1.0"
description = "A Git chatbot using Claude"

[tool.poetry.dependencies]
python = "^3.10"

[tool.setuptools]
packages = ["src"]